# Generated by Django 4.2.2 on 2023-06-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='places.places', verbose_name='Place')),
            ],
        ),
    ]
