# Generated by Django 4.2.2 on 2023-06-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_places_options_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='placeid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
