# Generated by Django 4.2.2 on 2023-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_places_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='short_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='places',
            name='placeid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PlaceId'),
        ),
    ]
