# Generated by Django 4.2.2 on 2023-06-15 06:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_places_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='placeid',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='PlaceId'),
        ),
    ]
