# Generated by Django 4.2.2 on 2023-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_places_description_long_alter_places_placeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='placeid',
            field=models.SlugField(max_length=100, verbose_name='PlaceId'),
        ),
    ]
