# Generated by Django 4.2.2 on 2023-06-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_places_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='short_title',
        ),
    ]
