# Generated by Django 4.2.2 on 2023-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_places_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
