# Generated by Django 4.2.2 on 2023-06-21 13:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_places_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
