# Generated by Django 4.2.2 on 2023-06-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_places_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='places.places', verbose_name='Place'),
        ),
    ]
