# Generated by Django 4.2.2 on 2023-06-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_images_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='placeid',
        ),
    ]
