# Generated by Django 4.2.2 on 2023-07-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_remove_places_placeid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
